language: node_js
node_js: node

before_install: cd web

script:
  - npm run build
  - mkdir deploy
  - cp -r dist vendor deploy
  - cp index.html deploy
  - touch deploy/.nojekyll

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: web/deploy
  keep_history: false
  fqdn: kale.maciej.ie
  on:
    branch: master
