[package]
name = "kale"
version = "0.1.0"
authors = ["Maciej Goszczycki <mgoszcz2@gmail.com>"]
edition = "2018"

[dependencies]
stdweb = "0.4.20"
itertools = "0.8.1"
log = "0.4.8"
web_logger = "0.2.0"